[project]
name = "mcp_server_browser_use"
version = "0.1.0"
description = "MCP server for browser-use"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "fastmcp>=0.4.1",
    "browser-use==0.1.19",
    "langchain>=0.3.14",
    "langchain-openai>=0.2.14",
    "pydantic>=2.10.5",
    "fastapi>=0.115.6",
    "uvicorn>=0.22.0",
    "openai>=1.59.5",
    "python-dotenv>=1.0.1",
    "pyperclip>=1.9.0",
    "langchain-ollama>=0.2.2",
]

[[project.authors]]
name = "Igor Tarasenko"
email = "tarasenko.igor.v@gmail.com"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
