[project]
name = "mcp_server_browser_use"
version = "0.1.0"
description = "A sample MCP server that integrates the browser-use library"
requires-python = ">=3.11"

dependencies = [
    "mcp>=1.0.0",
    "browser-use>=0.1.22",
    "langchain>=0.3.14",
    "langchain-openai>=0.2.14",
    "pydantic>=2.10.5",
    "fastapi>=0.115.6",
    "uvicorn>=0.22.0",
    "openai>=1.59.5",
    "python-dotenv>=1.0.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
mcp-server-browser-use = "mcp_server_browser_use:main"
